[package]
name = "code2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
rustc-serialize = "0.3.24"
kmeans = "0.2.0"
ndarray = "0.15.6"
serde = "1.0.150"
rand = "0.7"
